name: Java CI with Maven

on:
  push:
    branches: [ "**" ]

jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: shoppingMall-master/shoppingMall-master

    steps:
      # --- 1. 코드 체크아웃 ---
      - name: Checkout code
        uses: actions/checkout@v4

      # --- 2. JDK 17 설정 ---
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      # --- 3. Maven으로 빌드 및 테스트 ---
      - name: Build with Maven
        run: |
          chmod +x mvnw
          ./mvnw verify

      # --- 4. Docker 이미지 빌드 및 푸시 (main/master 브랜치 전용) ---
      - name: Build and Publish Docker Image
        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' }}
        run: |
          ./mvnw clean package -DskipTests=true
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t myimage:latest .
          docker tag myimage:latest ${{ secrets.DOCKER_USERNAME }}/shoppingmall-api:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/shoppingmall-api:latest
        env:
          DOCKER_BUILDKIT: 1
          DOCKER_CLI_EXPERIMENTAL: enabled

      # --- 5. 의존성 그래프 업데이트 ---
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@v4
        with:
          directory: shoppingMall-master/shoppingMall-master
